### ISSUE TITLE
Load previous page 

### ISSUE THREAD

**Issue by wbashir** [tmeasday/meteor-paginated-subscription#1]
Hi @tmeasday , I see there is a loadNextPage method, just wondering if there is also a loadPrevPage or something similar ?

**Comment by tmeasday** [comment]
Hi @warsamebashir -- no, this doesn't make sense right now as this package only does 'infinite-scroll-like' pagination (ie. the list just keeps getting bigger as you `loadNextPage`).

More than happy to accept PRs that make the behaviour an option.
