### ISSUE TITLE
Combining pagination with filtering/ sorting

### ISSUE THREAD

**Issue by lacco** [tmeasday/meteor-paginated-subscription#3]
I am building an application that should be able to list several thousand articles with infinite scrolling (using paginated-subscription). Additionally, the user should be able to filter/ sort this list, see http://meteor-paginated-subscription-example.meteor.com/ (https://github.com/lacco/meteor-paginated-subscription-example).

As you might recognize, clicking "Sort by priority" or "Load more" causes some weird flickering of the results. I think I understand why this happens (items are added and deleted from the collection step by step while reloading), but I have no idea how to avoid this issue. Additionally, when you have a look at the Firefox/ Chrome console, clicking "created at"/ "priority" causes Template.articles.rendered to be called several hundred times.

Can you help me out how to use paginated-subscription correctly with filtering/ sorting?

**Comment by tmeasday** [comment]
Hey @lacco - are you using `.fetch()` like we do in Telescope?

If so, I don't think you need to anymore as Meteor now supports proper sorted and limit-ed cursors. 

If you are using a cursor (as opposed to an array, the result of `.fetch()`), in an `{{#each}}` block, I don't think you'll see any flickering on either loading more or reordering (certainly not the first).

**Comment by lacco** [comment]
Hey @tmeasday , I am using `{{#each}}` without calling `.fetch()`, see https://github.com/lacco/meteor-paginated-subscription-example/blob/master/client/views/articles/index.js.coffee#L18 . So you would assume that this shouldn't cause the flickering? Just have a look at http://meteor-paginated-subscription-example.meteor.com/ and you'll recognize that there is flickering when reordering :).

**Comment by tmeasday** [comment]
Although this package isn't as efficient as it could be (it loads the entire data set each time rather than just the new records), I wouldn't expect, given the way meteor sets up the new subscription before tearing the old one down, that there'd be significant flickering if you use an `{{#each}}`.

You had to do some debugging of the rendering that's going on to say more. PS there's a good chance the behaviour may change in the upcoming UI release of Meteor.

**Comment by lacco** [comment]
Thank you for the hint to Meteor UI, think I'll just wait for the next meteor update and hope this get fixed. I am not so much into Meteor to debug the exact rendering process, so I just live with it :(
