### ISSUE TITLE
Deps is not defined

### ISSUE THREAD

**Issue by aaronjudd** [tmeasday/meteor-paginated-subscription#4]
Using paginated-subscription from inside a private package I get error:

```
Uncaught ReferenceError: Deps is not defined 
```

Adding the following to paginated-subscription/package.js

```
api.use('standard-app-packages');
```

Solved for me locally.

**Comment by tmeasday** [comment]
Probably more correct to `api.use('deps');`. Can you send a PR?

**Comment by aaronjudd** [comment]
I tested just adding deps, but still saw errors in console only standard-app-packages took care of all the errors  [added pull request](https://github.com/tmeasday/meteor-paginated-subscription/pull/5). Meant to link to this issue..but...
