### ISSUE TITLE
How do you handle changing queries?

### ISSUE THREAD

**Issue by Offlein** [tmeasday/meteor-paginated-subscription#7]
Like the plugin, but I'm confused about something that seems simple. I am using subscribeWithPagination() on my "registrants" collection, and let's say there are 100 published records and I load 5. My hypothetical user is looking for record #7. 

I have a "search" input in my app which runs a .find() query on "registrants" when its submit button is clicked. It should display only records that match the query.

If I make a search query that would find the 7th record, it won't display because it hasn't been loaded in the current page. If I click a button and trigger subscription handle.loadMore() and THEN make my query, the record will properly display.

Is this an error in my app logic, a shortcoming in meteor-paginated-subscription, or something it should handle that I just don't know about? Thanks!

**Comment by tmeasday** [comment]
Hi Craig,  

By the sounds of it, you need a separate subscription for your search results.

**Comment by Offlein** [comment]
Yep! For some reason it never occurred to me that I could have TWO subscriptions..! Thank you for the elementary Meteor training. :)
